title: Ryutaro Mori
description: <a href="https://ryutau.github.io/rm_cv_202309.pdf">CV</a><br><br><a href="https://ryutau.github.io">English</a> / <a href="https://ryutau.github.io/jp">日本語</a>
theme: jekyll-theme-minimal

exclude:
  - LICENSE
  - README.md
