title: Ryutaro Mori
description: >-
  <span class="sidebar-links"><a class="cv-link" href="/rm_cv_202410.pdf">CV</a><span class="language-links"><a href="/">English</a> / <a href="/jp">日本語</a></span></span>
theme: jekyll-theme-minimal

logo: /assets/img/myself.png

exclude:
  - LICENSE
  - README.md
  - vendor
  - vendor/
  - .bundle
