title: Ryutaro Mori
description: Welcome to my cheap web page.. \n<a href="https://ryutau.github.io">English</a>・<a href="https://ryutau.github.io/jp">日本語</a>
theme: jekyll-theme-minimal

exclude:
  - LICENSE
  - README.md
