title: Ryutaro Mori
description: <a href="https://ryutau.github.io">English</a>・<a href="https://ryutau.github.io/jp">日本語</a>・<a href="https://ryutau.github.io/mori_cv_202204.pdf">CV</a>
theme: jekyll-theme-minimal

exclude:
  - LICENSE
  - README.md
