title: Ryutaro Mori
description: Welcome to my cheap web page..[English](https://www.jstage.jst.go.jp/article/jrsj/40/1/40_40_25/_article/-char/ja/)
theme: jekyll-theme-minimal

exclude:
  - LICENSE
  - README.md
